server:
  port: 1111

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        jg-fanout-exchange:
          destination: jgFanoutExchange
      rabbit:
        bindings:
          jg-fanout-exchange:
            producer:
              exchangeType: fanout
      default:
        contentType: application/json
